# Generated by Django 5.2.5 on 2025-08-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_number_userdata_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
